<a href="https://colab.research.google.com/github/Lucas60229/PythonDataScience/blob/main/D01_Numpy_%E4%BD%9C%E6%A5%AD.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import operator

In [18]:
!pip3 install numpy==1.18.5

In [19]:
import numpy as np

In [28]:
arr = np.linspace(0,20,21,endpoint=True, dtype=int)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20])

In [21]:
arr[::2]

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [22]:
arr_3_times = arr[3::3]
arr_3_times

array([ 3,  6,  9, 12, 15, 18])