<a href="https://colab.research.google.com/github/Lucas60229/PythonDataScience/blob/main/D07.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

In [4]:
array1 = np.array([[10, 8], [3, 5]])

In [6]:
array1_inverse = np.linalg.inv(array1)
array1_inverse 

array([[ 0.19230769, -0.30769231],
       [-0.11538462,  0.38461538]])

In [9]:
array1_iden = array1 @ array1_inverse
array1_iden == np.identity(2)

array([[ True,  True],
       [ True,  True]])

In [10]:
array1_w, array1_v = np.linalg.eig(array1)
array1_w, array1_v

(array([13.,  2.]), array([[ 0.93632918, -0.70710678],
        [ 0.35112344,  0.70710678]]))

In [12]:
array1_u, array1_s, array1_vh = np.linalg.svd(array1)
array1_u, array1_s, array1_vh

(array([[-0.91663818, -0.39971796],
        [-0.39971796,  0.91663818]]),
 array([13.94721714,  1.86417116]),
 array([[-0.74319741, -0.6690722 ],
        [-0.6690722 ,  0.74319741]]))